log:
  level: DEBUG

accessLog: {}

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  enceladus-resolver:
    acme:
      httpChallenge:
        entryPoint: web-default
      email: "alex.nebula99@gmail.com"
      storage: /letsencrypt/acme.json
entryPoints:
  web-default:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
  web-secure:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "webapp-net"
    exposedByDefault: false
