api:
  dashboard: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  cassini:
    address: ":59749"
providers:
  docker:
    endpoint: "http://soxy-proxy:2375"
    network: "daphnis-net"
