services:
  actual-budget:
    image: actualbudget/actual-server:26.2.0
    container_name: actual-budget
    restart: unless-stopped
    volumes:
      - actual-budget-data:/data
    networks:
      - webapp-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual-budget.rule=Host(`budget.alexgs.me`)"
      - "traefik.http.routers.actual-budget.tls=true"
      - "traefik.http.routers.actual-budget.tls.certresolver=enceladus-resolver"
      - "traefik.http.services.actual-budget.loadbalancer.server.port=5006"

  convex:
    image: ghcr.io/alexgs/convex:latest
    container_name: convex
    restart: unless-stopped
    env_file: convex.env
    volumes:
      - logs:/app/logs
    networks:
      - webapp-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convex.rule=Host(`convex.alexgs.me`)"
      - "traefik.http.routers.convex.tls=true"
      - "traefik.http.routers.convex.tls.certresolver=enceladus-resolver"
      - "traefik.http.services.convex.loadbalancer.server.port=4322"

  skyreach:
    image: ghcr.io/alexgs/skyreach:main
    container_name: skyreach
    restart: unless-stopped
    env_file: skyreach.env
    networks:
      - webapp-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skyreach.rule=Host(`skyreach.alexgs.me`)"
      - "traefik.http.routers.skyreach.tls=true"
      - "traefik.http.routers.skyreach.tls.certresolver=enceladus-resolver"
      - "traefik.http.services.skyreach.loadbalancer.server.port=4321"

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.4
    container_name: plausible
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    env_file:
      - plausible.env
    networks:
      - webapp-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.rule=Host(`analytics.automatacodex.com`)"
      - "traefik.http.routers.plausible.tls=true"
      - "traefik.http.routers.plausible.tls.certresolver=enceladus-resolver"
      - "traefik.http.services.plausible.loadbalancer.server.port=8000"

  plausible_db:
    image: postgres:16-alpine
    container_name: plausible_db
    restart: unless-stopped
    volumes:
      - plausible-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - webapp-net

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    container_name: plausible_events_db
    restart: unless-stopped
    volumes:
      - plausible-event-data:/var/lib/clickhouse
      - plausible-event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - webapp-net

  webserver:
    image: traefik:3.6
    container_name: webserver
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - "127.0.0.1:8080:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - actual-budget
      - convex
      - skyreach
    networks:
      - webapp-net

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      device: /home/alexgs/devops/enceladus/logs/
      o: bind
  actual-budget-data:
    driver: local
    driver_opts:
      type: none
      device: /home/alexgs/devops/enceladus/actual-budget-data/
      o: bind
  plausible-db-data:
  plausible-event-data:
  plausible-event-logs:

networks:
  webapp-net:
    driver: bridge
    name: webapp-net
