services:
  convex:
    image: ghcr.io/alexgs/convex:latest
    container_name: convex
    restart: unless-stopped
    env_file: convex.env
    volumes:
      - logs:/app/logs
    networks:
      - webapp-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convex.rule=Host(`convex.alexgs.me`)"
      - "traefik.http.routers.convex.tls=true"
      - "traefik.http.routers.convex.tls.certresolver=enceladus-resolver"
      - "traefik.http.services.convex.loadbalancer.server.port=4322"

  skyreach:
    image: ghcr.io/alexgs/skyreach:main
    container_name: skyreach
    restart: unless-stopped
    env_file: skyreach.env
    networks:
      - webapp-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skyreach.rule=Host(`skyreach.alexgs.me`)"
      - "traefik.http.routers.skyreach.tls=true"
      - "traefik.http.routers.skyreach.tls.certresolver=enceladus-resolver"
      - "traefik.http.services.skyreach.loadbalancer.server.port=4321"

  webserver:
    image: traefik:3.6
    container_name: webserver
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - "127.0.0.1:8080:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - convex
      - skyreach
    networks:
      - webapp-net

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      device: /home/alexgs/devops/enceladus/logs/
      o: bind

networks:
  webapp-net:
    driver: bridge
    name: webapp-net
