version: '3'

vars:
  CONVEX_SERVICE: convex

dotenv: ['.env']

tasks:
  down:
    cmds:
      - docker-compose down --remove-orphans
    desc: Tear down the application

  up:
    cmds:
      - docker-compose up -d
    desc: Spin-up the application

  # --- CONVEX COMMANDS ---

  convex:logs:
    cmds:
      - "docker-compose logs -f {{.CONVEX_SERVICE}}"
    desc: Follow logs for Convex service

  convex:restart:
    cmds:
      - "docker-compose restart {{.CONVEX_SERVICE}}"
    desc: Restart Convex service

  convex:shell:
    cmds:
      - "docker exec -it {{.CONVEX_SERVICE}} sh"
    desc: Open a shell on the Convex container

  convex:update:
    cmds:
      - docker pull ghcr.io/alexgs/convex:latest
      - docker-compose up -d {{.CONVEX_SERVICE}}
    desc: Pull latest Convex image and restart service

  # --- TRAEFIK COMMANDS ---

  traefik:logs:
    cmds:
      - "docker-compose logs -f webserver"
    desc: Follow logs for Traefik service
