services:
  database:
    image: postgres:13-alpine
    container_name: database
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - "${DATABASE_DIRECTORY_POSTGRES}:/var/lib/postgresql/data"
    networks:
      - webapp-net

  dnd-compendium:
    image: alexgs99/dnd-compendium:1.0.0
    container_name: dnd-compendium
    restart: unless-stopped
    env_file: dnd-compendium.env
    networks:
      - webapp-net
    labels:
      - "traefik.http.routers.dnd-compendium.rule=Host(`compendium.owlbear.tech`)"
      - "traefik.http.routers.dnd-compendium.tls=true"
      - "traefik.http.routers.dnd-compendium.tls.certresolver=daphnis-resolver"
      - "traefik.http.services.dnd-compendium.loadbalancer.server.port=3000" # TODO Update Dockerfile to expose only this port

  electric-lounge:
    image: alexgs99/electric-lounge:0.2.0
    container_name: electric-lounge
    restart: unless-stopped
    env_file: electric-lounge.env
    volumes:
      - logs:/home/node/logs
    networks:
      - webapp-net
    labels:
      - "traefik.http.routers.electric-lounge.rule=Host(`electriclounge.owlbear.tech`)"
      - "traefik.http.routers.electric-lounge.tls=true"
      - "traefik.http.routers.electric-lounge.tls.certresolver=daphnis-resolver"

  # https://github.com/Tecnativa/docker-socket-proxy
  soxy-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: soxy-proxy
    networks:
      - socker-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1

  webserver:
    image: traefik:2.4
    container_name: webserver
    restart: unless-stopped
    environment:
      - DO_AUTH_TOKEN
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./traefik:/etc/traefik
    depends_on:
      - dnd-compendium
      - electric-lounge
      - soxy-proxy
    networks:
      - webapp-net
      - socker-net

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      device: /home/alexgs/devops/daphnis/logs/
      o: bind

networks:
  webapp-net:
    driver: bridge
    name: webapp-net
  socker-net:
    driver: bridge
    driver_opts:
      encrypted: 'true' # We're passing Docker socket stuff over TCP, so encrypt
    name: socker-net
